# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Tribuo: Machine Learning in Java"
email: tribuo-devel@oracle.com
description: >- # this means to ignore newlines until "baseurl:"
  Tribuo is a Java ML library for
  multi-class classification, regression, clustering, anomaly detection and
  multi-label classification.
logo: "/assets/img/tribuo-logo-color.svg"
og-logo: "/assets/img/tribuo-logo-color-1200.png"
twitter-logo: "/assets/img/tribuo-logo-only-512.png"
twitter-handle: "@oraclelabs"
og-tags:
  - java
  - nlp
  - machine-learning
  - deep-learning
  - clustering
  - regression
  - classification
  - multi-label
  - onnx
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://tribuo.org"
tribuo_version: 4.3.0 # Current version of Tribuo library.
repository_url: "https://github.com/oracle/tribuo.git"
javadocs: "https://tribuo.org/learn/4.2/javadoc/index.html" # Path to index.html
javadoc_root: "https://tribuo.org/learn/4.2/javadoc/" # Path to top of class hierarchy

# We'll use collections to manage doc versions
# This will take care of getting the URLs right
# without having to make changes everywhere. The current
# version will be a site-wide variable we can use.
doc_version: 4.3
doc_versions: [4.0, 4.1, 4.2, 4.3] # a comma-separated list of decimal values

defaults:
  -
    scope:
      path: "/learn/4.3/*"
      type: "pages"
    values:
      layout: learn
      version: 4.3
      active: learn
  -
    scope:
      path: "/learn/4.2/*"
      type: "pages"
    values:
      layout: learn-outdated
      version: 4.2
      active: learn
      sitemap:
        priority: 0.25
  -
    scope:
      path: "/learn/4.1/*"
      type: "pages"
    values:
      layout: learn-outdated
      version: 4.1
      active: learn
      sitemap:
        priority: 0.25
  -
    scope:
      path: "/learn/4.0/*"
      type: "pages"
    values:
      layout: learn-outdated
      version: 4.0
      active: learn
      sitemap:
        priority: 0.25
  -
    scope:
      path: "learn/*/tutorials/*"
      type: pages
    values:
      description: "Learn how to use some of Tribuo's features with simple notebook-based tutorials."


# Build settings
markdown: kramdown
plugins:
#- jekyll-feed

# My settings
search_enabled: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: [
  "node_modules/",
  "*.gemspec",
  "*.gem",
  "Gemfile",
  "Gemfile.lock",
  "package.json",
  "package-lock.json",
  "script/",
  "LICENSE.txt",
  "lib/",
  "bin/",
  "tribuo/",
  "README.md",
  "Rakefile",
  "*~",
  "*.iml",
  ".idea"
]

